Final Project/SonyPassionWeb/SonyPassionWeb/Models/SonyPassion.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SonyPassionWeb.Models
{
    public class SonyPassion
    {
        public int SonyPassionID { get; set; }

        //
        public virtual ICollection<News> News { get; set; }
    }
}

Final Project/SonyPassionWeb/SonyPassionWeb/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SonyPassionWeb.Models;

namespace SonyPassionWeb.Controllers
{
    [Authorize]
    public class NewsController : Controller
    {
        private SonyPassionDbContext db = new SonyPassionDbContext();

        //
        // GET: /News/
        [AllowAnonymous]
        public ActionResult Index()
        {
            var news = db.News.Include(n => n.SonyPassion).Include(n => n.Xperia).Include(n => n.SmartWatch).Include(n => n.HeadphonesEarbuds).Include(n => n.Video).Include(n => n.UserProfile);
            return View(news.ToList());
        }

        //
        // GET: /News/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = 0)
        {
            News news = db.News.Find(id);
            ViewData["idnews"] = id;
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        //
        // GET: /News/Create

        public ActionResult Create()
        {
            ViewBag.SonyPassionID = new SelectList(db.SonyPassions, "SonyPassionID", "SonyPassionID");
            ViewBag.XperiaID = new SelectList(db.Xperia, "XperiaID", "XperiaID");
            ViewBag.SmartWatchID = new SelectList(db.SmartWatch, "SmartWatchID", "SmartWatchID");
            ViewBag.HeadphonesEarbudsID = new SelectList(db.HeadphonesEarbuds, "HeadphonesEarbudsID", "HeadphonesEarbudsID");
            ViewBag.VideoID = new SelectList(db.Video, "VideoID", "VideoID");
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName");
            return View();
        }

        //
        // POST: /News/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(News news, string Content)
        {
            if (ModelState.IsValid)
            {
                news.DateUpLoad = DateTime.Now;
                int userid = db.UserProfiles.Select(x => new { x.UserId, x.UserName }).Where(y => y.UserName == User.Identity.Name).Single().UserId;
                news.UserProfileUserId = userid;
                List<Tag> Tags = new List<Tag>();
                string[] TagContent = Content.Split(',');
                foreach (string item in TagContent)
                {
                    Tag tagExits = null;
                    var ListTag = db.Tag.Where(y => y.Content.Equals(item));
                    if (ListTag.Count() > 0)
                    {
                        tagExits = ListTag.First();
                        tagExits.News.Add(news);
                    }
                    else
                    {
                        tagExits = new Tag();
                        tagExits.Content = item;
                        tagExits.News = new List<News>();
                        tagExits.News.Add(news);
                    }
                    Tags.Add(tagExits);
                }
                news.Tags = Tags;
                db.News.Add(news);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SonyPassionID = new SelectList(db.SonyPassions, "SonyPassionID", "SonyPassionID", news.SonyPassionID);
            ViewBag.XperiaID = new SelectList(db.Xperia, "XperiaID", "XperiaID", news.XperiaID);
            ViewBag.SmartWatchID = new SelectList(db.SmartWatch, "SmartWatchID", "SmartWatchID", news.SmartWatchID);
            ViewBag.HeadphonesEarbudsID = new SelectList(db.HeadphonesEarbuds, "HeadphonesEarbudsID", "HeadphonesEarbudsID", news.HeadphonesEarbudsID);
            ViewBag.VideoID = new SelectList(db.Video, "VideoID", "VideoID", news.VideoID);
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", news.UserProfileUserId);
            return View(news);
        }

        //
        // GET: /News/Edit/5

        public ActionResult Edit(int id = 0)
        {
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            ViewBag.SonyPassionID = new SelectList(db.SonyPassions, "SonyPassionID", "SonyPassionID", news.SonyPassionID);
            ViewBag.XperiaID = new SelectList(db.Xperia, "XperiaID", "XperiaID", news.XperiaID);
            ViewBag.SmartWatchID = new SelectList(db.SmartWatch, "SmartWatchID", "SmartWatchID", news.SmartWatchID);
            ViewBag.HeadphonesEarbudsID = new SelectList(db.HeadphonesEarbuds, "HeadphonesEarbudsID", "HeadphonesEarbudsID", news.HeadphonesEarbudsID);
            ViewBag.VideoID = new SelectList(db.Video, "VideoID", "VideoID", news.VideoID);
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", news.UserProfileUserId);
            return View(news);
        }

        //
        // POST: /News/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(News news)
        {
            if (ModelState.IsValid)
            {
                db.Entry(news).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SonyPassionID = new SelectList(db.SonyPassions, "SonyPassionID", "SonyPassionID", news.SonyPassionID);
            ViewBag.XperiaID = new SelectList(db.Xperia, "XperiaID", "XperiaID", news.XperiaID);
            ViewBag.SmartWatchID = new SelectList(db.SmartWatch, "SmartWatchID", "SmartWatchID", news.SmartWatchID);
            ViewBag.HeadphonesEarbudsID = new SelectList(db.HeadphonesEarbuds, "HeadphonesEarbudsID", "HeadphonesEarbudsID", news.HeadphonesEarbudsID);
            ViewBag.VideoID = new SelectList(db.Video, "VideoID", "VideoID", news.VideoID);
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", news.UserProfileUserId);
            return View(news);
        }

        //
        // GET: /News/Delete/5

        public ActionResult Delete(int id = 0)
        {
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        //
        // POST: /News/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            News news = db.News.Find(id);
            db.News.Remove(news);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Final Project/SonyPassionWeb/SonyPassionWeb/Controllers/SonyPassionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SonyPassionWeb.Models;

namespace SonyPassionWeb.Controllers
{
    public class SonyPassionController : Controller
    {
        private SonyPassionDbContext db = new SonyPassionDbContext();

        //
        // GET: /SonyPassion/

        public ActionResult Index()
        {
            return View(db.SonyPassions.ToList());
        }

        //
        // GET: /SonyPassion/Details/5

        public ActionResult Details(int id = 0)
        {
            SonyPassion sonypassion = db.SonyPassions.Find(id);
            ViewData["idnewss"] = id;
            if (sonypassion == null)
            {
                return HttpNotFound();
            }
            return View(sonypassion);
        }

        //
        // GET: /SonyPassion/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /SonyPassion/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SonyPassion sonypassion)
        {
            if (ModelState.IsValid)
            {
                db.SonyPassions.Add(sonypassion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sonypassion);
        }

        //
        // GET: /SonyPassion/Edit/5

        public ActionResult Edit(int id = 0)
        {
            SonyPassion sonypassion = db.SonyPassions.Find(id);
            if (sonypassion == null)
            {
                return HttpNotFound();
            }
            return View(sonypassion);
        }

        //
        // POST: /SonyPassion/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SonyPassion sonypassion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sonypassion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sonypassion);
        }

        //
        // GET: /SonyPassion/Delete/5

        public ActionResult Delete(int id = 0)
        {
            SonyPassion sonypassion = db.SonyPassions.Find(id);
            if (sonypassion == null)
            {
                return HttpNotFound();
            }
            return View(sonypassion);
        }

        //
        // POST: /SonyPassion/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SonyPassion sonypassion = db.SonyPassions.Find(id);
            db.SonyPassions.Remove(sonypassion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Final Project/SonyPassionWeb/SonyPassionWeb/Views/SonyPassion/Create.cshtml
@model SonyPassionWeb.Models.SonyPassion

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>SonyPassion</legend>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Final Project/SonyPassionWeb/SonyPassionWeb/Views/SonyPassion/Delete.cshtml
@model SonyPassionWeb.Models.SonyPassion

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>SonyPassion</legend>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Final Project/SonyPassionWeb/SonyPassionWeb/Views/SonyPassion/Details.cshtml
@model SonyPassionWeb.Models.SonyPassion

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>SonyPassion</legend>
</fieldset>

<fieldset>
        @foreach(var news in Model.News)
        {
            <div class="display-field">
                <h2>@Html.ActionLink(news.Title,"Details/" + news.NewsID,"News")</h2>
            </div>
            <div class="display-field">
                @Html.DisplayFor(n => news.Body)
            </div>
        }
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.SonyPassionID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Final Project/SonyPassionWeb/SonyPassionWeb/Views/SonyPassion/Edit.cshtml
@model SonyPassionWeb.Models.SonyPassion

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>SonyPassion</legend>

        @Html.HiddenFor(model => model.SonyPassionID)

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Final Project/SonyPassionWeb/SonyPassionWeb/Views/SonyPassion/Index.cshtml
@model IEnumerable<SonyPassionWeb.Models.SonyPassion>

@{
    ViewBag.Title = "SonyPassion";
}

@*<h2>Sony Passion</h2>*@

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@

@Html.Partial("_ViewNews",new SonyPassionWeb.Models.News(),ViewData)



@*<table>
<tr>
</tr>

@foreach (var item in Model) {
    <tr>
        <td>
            
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.SonyPassionID }) |
            @Html.ActionLink("Details", "Details", new { id=item.SonyPassionID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.SonyPassionID })
        </td>
    </tr>
}
</table>*@

Final Project/SonyPassionWeb/SonyPassionWeb/Views/SonyPassion/_ViewNews.cshtml
@model SonyPassionWeb.Models.News
@Styles.Render("~/Content/Style.css")
<div class="container">
    <div class="box-border">
        <div class="box-news-left" >
            <div class="title">
                <h2> @Html.ActionLink("> Xperia Z3 đã giúp các bác sĩ ở Châu Phi phát hiện các bệnh về mắt", "Details/5", "News") </h2>
            </div>
            <div class="info" >
                <div class="info-deltail">
                    Posted at 12/4/2014 8:45:55 PM by <div style="color: blue; display: inline;">
                    <a href="http://localhost:51244/Account/Manage" id="account" style="color: #2185ff;"> nguyen </a> 
                    </div>
                </div>
            </div>
            <div class="content">
                <p>
                    <img class="Text-Wrap" src="../../Images/z3_eyes-640x360.jpg" width="200" height="130" />
                    Chúng ta thường coi Xperia như một chiếc smartphone để giải trí và liên lạc cá nhân, nhưng giá trị của nó đâu có đơn giản chỉ có vậy.
                    Tại Châu Phi, Xperia Z3 đã góp phần không nhỏ cho cộng đồng khi nó đã được chọn để đồng hành với các bác sĩ nhãn khoa thăm khám và chữa các bệnh về mắt cho những người dân nghèo ở đây.
                </p>
            </div>
            <div class="other" style="border-top: 1px solid #d3d3d3; padding: 10px; padding-top: 7px; text-align:right;">
                @Html.ActionLink("Read On -->>", "Details/5", "News")
            </div>
        </div>
        <div class="box-news-right">
            <div class="title">
                <h2> @Html.ActionLink("> Mở hộp SmartWatch 3 đầu tiên tại Việt Nam", "Details/6", "News") </h2>
            </div>
            <div class="info">
                <div class="info-deltail">
                    Posted at 12/5/2014 10:25:47 PM by <div style="color: blue; display: inline;">
                    <a href="http://localhost:51244/Account/Manage" id="account" style="color: #2185ff;"> nguyen </a>
                     </div>
                </div>
            </div>
            <div class="content">
                <p>
                    <img class="Text-Wrap" src="../Images/mo_hop_smartwacth_3_241.jpg" width="200" height="130" />Ra mắt hồi tháng 9 vừa qua tại sự kiện IFA 2014 và mới chỉ bán hạn chế một số thị trường nhưng chiếc đồng thông minh thế hệ mới nhất của Sony là SmartWacth 3 đã đặt chân tới Việt Nam thông qua cửa hàng XperiaShop.vn.
                    SmartWacth 3 được chú ý bởi đây là thiết bị đeo tay đầu tiên của Sony chạy nền tảng hệ điều hành Android Wear giống như trên các đồng hồ thông minh ra mắt gần đây như Moto 360, LG G Watch.
                </p>
            </div>
            <div class="other" style="border-top: 1px solid #d3d3d3; padding: 10px; padding-top: 7px; text-align:right;">
                @Html.ActionLink("Read On -->>", "Details/6", "News")
            </div>
        </div>
    </div>

    <div class="box-border">
        <div class="box-news-left">
            <div class="title">
                <h2> @Html.ActionLink("> Xperia Z3, Z3 Compact chuẩn bị có FW mới (23.0.1.A.5.77)", "Details/7", "News") </h2>
            </div>
            <div class="info">
                <div class="info-deltail">
                    Posted at 12/5/2014 10:27:42 PM by <div style="color: blue; display: inline;">
                    <a href="http://localhost:51244/Account/Manage" id="account" style="color: #2185ff;"> nguyen </a> 
                    </div>
                </div>
            </div>
            <div class="content">
                <p>
                    <img class="Text-Wrap" src="../Images/xperia_z3_copper.png" width="200" height="130" />Bộ đôi Xperia cao cấp nhất hiện nay đang được Sony chăm chút phần mềm khá thương xuyên, sắp tới bộ đôi này sẽ được nâng cấp từ bản 23.0.A.2.105 lên bản 23.0.1.A.5.77.
                     Đây là bản cập nhật nhỏ tập trung vào tối ưu hóa FW cũng như fix các lỗi nhỏ người dùng báo cáo thời gian qua.
                </p>
            </div>
            <div class="other" style="border-top: 1px solid #d3d3d3; padding: 10px; padding-top: 7px; text-align:right;">
                @Html.ActionLink("Read On -->>", "Details/7", "News")
            </div>
        </div>
        <div class="box-news-right">
            <div class="title">
                <h2> @Html.ActionLink("> Xperia Z Ultra Google Edition đã được lên Android 5.0", "Details/8", "News") </h2>
            </div>
            <div class="info">
                <div class="info-deltail">
                    Posted at 12/5/2014 10:29:45 PM by <div style="color: blue; display: inline;">
                      <a href="http://localhost:51244/Account/Manage" id="account" style="color: #2185ff;"> nguyen </a> 
                    </div>
                </div>
            </div>
            <div class="content">
                <p>
                    <img class="Text-Wrap" src="../Images/sony-xperia-z-ultra.jpg" width="200" height="130" />Đại diện duy nhất của Sony góp mặt trong series dòng máy Google Play Edition được hỗ trợ nâng cấp FW trực tiếp từ Google đã chính thức được lên hệ điều hành Android 5.0 mới nhất,
                     trong khi đó những người anh em khác phải đợi Sony tới đầu năm sau mới được cập nhật.
                </p>
            </div>
            <div class="other" style="border-top: 1px solid #d3d3d3; padding: 10px; padding-top: 7px; text-align:right;">
                @Html.ActionLink("Read On -->>", "Details/8", "News")
            </div>
        </div>
    </div>

    <div class="box-border">
            <div class="box-news-left">
                <div class="title">
                    <h2> @Html.ActionLink("> Xperia Z1, Z2, Z3 chính hãng đồng loạt giảm giá tới 1,5tr đồng", "Details/9", "News") </h2>
                </div>
                <div class="info">
                    <div class="info-deltail">
                       Posted at 12/5/2014 10:30:52 PM by <div style="color: blue; display: inline;">
                        <a href="http://localhost:51244/Account/Manage" id="account" style="color: #2185ff;"> nguyen </a> 
                        </div>
                    </div>
                </div>
                <div class="content">
                    <p>
                        <img class="Text-Wrap" src="../Images/sony-xperia-z2-vs-xperia-z1.jpg" width="200" height="130" />Xperia Z3 đã giảm độ nóng, nhất là sự xuất hiện của iPhone 6 chính hãng có giá tương đối tốt nên việc Sony Việt Nam giảm giá Xperia Z3 là điều khá dễ hiểu.
                         Kéo theo đó là các mẫu máy thấp hơn như Z2, Z1 cũng được giảm giá theo.
                    </p>
                </div>
                <div class="other" style="border-top: 1px solid #d3d3d3; padding: 10px; padding-top: 7px; text-align:right;">
                    @Html.ActionLink("Read On -->>", "Details/9", "News")
                </div>
            </div>
        <div class="box-news-right">
            <div class="title">
                <h2> @Html.ActionLink("> SmartBand Talk, SmartWatch 3 có giá 4tr1 và 6tr2 tại Đài Loan", "Details/10", "News") </h2>
            </div>
            <div class="info">
                <div class="info-deltail">
                    Posted at 12/5/2014 10:32:43 PM by <div style="color: blue; display: inline;">
                    <a href="http://localhost:51244/Account/Manage" id="account" style="color: #2185ff;"> nguyen </a>
                     </div>
                </div>
            </div>
            <div class="content">
                <p>
                    <img class="Text-Wrap" src="../Images/smartband_talk.jpg" width="200" height="130" />Thị trường mệnh danh có giá bán các sản phẩm của Sony Mobile tốt nhất tại khu vực Châu Á. Tuy nhiên đối với thiết bị đeo tay thì có vẻ không phải vậy.
                     Mức giá vòng đeo tay SmartBand Talk tại Đài Loan được định giá 5.990 Đài tệ tương đương 4,1tr đồng, đồng hồ SmartWatch 3 có giá cao hơn ở mức 8.990 Đài tệ tương đương 6,2tr đồng.
                </p>
            </div>
            <div class="other" style="border-top: 1px solid #d3d3d3; padding: 10px; padding-top: 7px; text-align:right;">
                @Html.ActionLink("Read On -->>", "Details/10", "News")
            </div>
        </div>   
    </div>
    <div class="box-border">
        <div class="box-news-left">
            <div class="title">
                <h2> @Html.ActionLink("> Mở hộp tai nghe hàng khủng XBA-Z5, giá 12tr8", "Details/11", "News") </h2>
            </div>
            <div class="info">
                <div class="info-deltail">
                    Posted at 12/5/2014 10:30:52 PM by <div style="color: blue; display: inline;">
                        <a href="http://localhost:51244/Account/Manage" id="account" style="color: #2185ff;"> nguyen </a>
                    </div>
                </div>
            </div>
            <div class="content">
                <p>
                    <img class="Text-Wrap" src="../Images/xba_z5_unbox_15.jpg" width="200" height="130" />Đôi với những người chơi âm thanh thì việc đầu tư một chiếc máy nghe nhạc như Walkman ZX1 có giá tầm 18tr đồng thì sắm thêm một chiếc tai nghe có giá 12,8tr như chiếc MDR-Z5 dưới đây thì cũng nên chỉ coi là việc nên làm và “quá là điều bình thường luôn”.
                    Bỏ ra một số tiền lớn, tất nhiên bạn sẽ nhật được một chiếc tai nghe có giá trị xứng tầm, âm thanh đỉnh cao, “Made in Japan” chất lượng. Dưới đây là loạt hình ảnh mở hộp chiếc tai nghe này tại Nhật Bản. Phụ kiện đi kèm gồm có bao da, nhiều típ với size khác nhau, dây đôi thông thường và một bộ dây đơn để kết nối với headamp cao cấp.
                </p>
            </div>
            <div class="other" style="border-top: 1px solid #d3d3d3; padding: 10px; padding-top: 7px; text-align:right;">
                @Html.ActionLink("Read On -->>", "Details/11", "News")
            </div>
        </div>
        <div class="box-news-right">
            <div class="title">
                <h2> @Html.ActionLink("> Trên tay bộ đôi Walkman A15, A17 tại VN, giá từ 4tr5", "Details/12", "News") </h2>
            </div>
            <div class="info">
                <div class="info-deltail">
                    Posted at 12/5/2014 10:32:43 PM by <div style="color: blue; display: inline;">
                        <a href="http://localhost:51244/Account/Manage" id="account" style="color: #2185ff;"> nguyen </a>
                    </div>
                </div>
            </div>
            <div class="content">
                <p>
                    <img class="Text-Wrap" src="../Images/tren_tay_walkman_a15_1.jpg" width="200" height="130" />Cũng tại sự kiện IFA 2014 tổ chức hồi tháng 9 vừa qua, Sony đã bổ sung cho gia đình Walkman của mình thêm một model mới là Walkman A15 và A17. Về cơ bản 2 mẫu này đều giống nhau chỉ khác về dung lượng bộ nhớ lần lượt là 16GB và 32GB.
                </p>
            </div>
            <div class="other" style="border-top: 1px solid #d3d3d3; padding: 10px; padding-top: 7px; text-align:right;">
                @Html.ActionLink("Read On -->>", "Details/12", "News")
            </div>
        </div>   
     </div>
 </div>